const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';
const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
const ADD_THREAD_FAIL = 'ADD_THREAD_FAIL';
const ADD_THREAD_SUCCESS = 'ADD_THREAD_SUCCESS';
const DELETE_REPLY_FAIL = 'DELETE_REPLY_FAIL';
const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS';
const DELETE_THREAD_FAIL = 'DELETE_THREAD_FAIL';
const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS';
const EDIT_REPLY_FAIL = 'EDIT_REPLY_FAIL';
const EDIT_REPLY_SUCCESS = 'EDIT_REPLY_SUCCESS';
const EDIT_THREAD_FAIL = 'EDIT_THREAD_FAIL';
const EDIT_THREAD_SUCCESS = 'EDIT_THREAD_SUCCESS';
const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_UP_FAIL = 'SIGN_IN_SUCCESS';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export {
  ADD_REPLY_FAIL,
  ADD_REPLY_SUCCESS,
  ADD_THREAD_FAIL,
  ADD_THREAD_SUCCESS,
  DELETE_REPLY_FAIL,
  DELETE_REPLY_SUCCESS,
  DELETE_THREAD_FAIL,
  DELETE_THREAD_SUCCESS,
  EDIT_REPLY_FAIL,
  EDIT_REPLY_SUCCESS,
  EDIT_THREAD_FAIL,
  EDIT_THREAD_SUCCESS,
  SIGN_IN_FAIL,
  SIGN_OUT_FAIL,
  SIGN_OUT_SUCCESS,
  SIGN_IN_SUCCESS,
  SIGN_UP_FAIL,
  SIGN_UP_SUCCESS,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAIL,
};
