const ADD_THREAD_FAIL = 'ADD_THREAD_FAIL';
const ADD_THREAD_SUCCESS = 'ADD_THREAD_SUCCESS';
const GET_THREADS_FAIL = 'GET_THREADS_FAIL';
const GET_THREADS_SUCCESS = 'GET_THREADS_SUCCESS';
const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_UP_FAIL = 'SIGN_IN_SUCCESS';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export {
  ADD_THREAD_FAIL,
  ADD_THREAD_SUCCESS,
  GET_THREADS_FAIL,
  GET_THREADS_SUCCESS,
  SIGN_IN_FAIL,
  SIGN_OUT_SUCCESS,
  SIGN_IN_SUCCESS,
  SIGN_UP_FAIL,
  SIGN_UP_SUCCESS,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAIL,
};
